<?php


namespace App\Controller;


use App\Entity\Location;
use App\Form\RegistrationType;
use App\Security\LoginFormAuthenticator;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Security\Guard\GuardAuthenticatorHandler;

class RegistrationController extends Controller
{
    /**
     * @Route("/register", name="registration")
     */
    public function registrationAction(Request $request, GuardAuthenticatorHandler $guardAuthenticatorHandler, LoginFormAuthenticator $formAuthenticator)
    {
        $form = $this->createForm(RegistrationType::class);

        $form->handleRequest($request);


        if ($form->isSubmitted() && $form->isValid()) {
            $userData = $form->getData();
            $file = $userData->getActivity()->getPathToLogo();
            $em = $this->getDoctrine()->getManager();


            $fileName = $this->generateUniqueFileName().'.'.$file->guessExtension();
            $file->move(
                $this->getParameter('uploads_directory'),
                $fileName
            );

            $userData->getActivity()->setPathToLogo($fileName);

            $location = $userData->getActivity()->getLocation();
            $locationFound = $em->getRepository(Location::class)->findLocationByLocation($location);
            if($locationFound) {
                $userData->getActivity()->setLocation($locationFound);
            }

            $em->persist($userData);
            $em->flush();

            return $guardAuthenticatorHandler->authenticateUserAndHandleSuccess(
                    $userData,
                    $request,
                    $formAuthenticator,
                    'main'
                );
        }

        return $this->render('security/register.html.twig', [
            'form' => $form->createView()
        ]);
    }

    /**
     * @return string
     */
    private function generateUniqueFileName()
    {
        // md5() reduces the similarity of the file names generated by
        // uniqid(), which is based on timestamps
        return md5(uniqid());
    }
}